import { useCallback, useEffect, useRef, useState } from 'react';
import { LayoutDashboard, FileText, Library, MessageSquare, FileDown, Settings, LogOut, ArrowUpRight, Fingerprint, Menu, Plus } from 'lucide-react';
import { AuthScreen } from './components/AuthScreen';
import { authClient } from './services/authClient';
import type { SessionUser } from './services/authClient';
import { pilotApi } from './services/pilotClient';
import type { Project, ProjectDetail, Review, Source } from './pilotTypes';
import { ProposalEditor, SourcesPanel, ReviewPanel, ReportPanel } from './components/PilotWorkspace';
import type { Act } from './components/PilotWorkspace';
import { readable } from './components/PilotEvidence';
import { parsePilotRoute, pilotHash, selectedVersion } from './services/pilotNavigation';
import { clearDrafts, removeDraft } from './services/pilotDrafts';
import './PilotApp.css';

const navigation = [ ['dashboard', 'Dashboard', LayoutDashboard], ['proposals', 'Proposals', FileText], ['sources', 'Sources & Evidence', Library], ['reviews', 'Reviews', MessageSquare], ['reports', 'Reports', FileDown], ['settings', 'Settings', Settings] ] as const;
type View = typeof navigation[number][0];
const parseRoute = () => parsePilotRoute(location.hash);

function AccountSettings({ user, setUser, act, busy }: { user: SessionUser; setUser: (u: SessionUser) => void; act: Act; busy: boolean }) {
  const [name, setName] = useState(user.name), [org, setOrg] = useState(user.organization || ''), [email, setEmail] = useState(''), [role, setRole] = useState('Reviewer');
  const [legacy, setLegacy] = useState<{ id: string; title: string; description: string }[]>([]), [inspected, setInspected] = useState(false);
  return <><div className="panel"><h2>Your profile</h2><p>{user.email} · {user.role}</p><form onSubmit={e => { e.preventDefault(); void act(async () => setUser(await authClient.profile(name, org)), 'Profile updated.'); }}><label>Full name<input required value={name} onChange={e => setName(e.target.value)} maxLength={100} /></label><label>Organization<input value={org} onChange={e => setOrg(e.target.value)} maxLength={160} /></label><button disabled={busy}>Save profile</button></form><div className="button-row"><button disabled={busy} onClick={() => void act(async () => { const r = await authClient.forgot(user.email); alert(r.message); })}>Send password recovery link</button>{!user.verified && <button disabled={busy} onClick={() => void act(async () => { const r = await authClient.resendVerification(user.email); alert(r.message); })}>Send verification link</button>}</div></div>
    {user.role === 'Administrator' && <div className="panel"><h2>Invite a team member</h2><p className="muted">Invitations expire after 24 hours and are bound to the recipient’s email.</p><form onSubmit={e => { e.preventDefault(); void act(async () => { const r = await pilotApi<{ message: string }>('/admin/invitations', { email, role }); setEmail(''); alert(r.message); }); }}><label>Email<input type="email" required value={email} onChange={e => setEmail(e.target.value)} /></label><label>Role<select value={role} onChange={e => setRole(e.target.value)}><option>Reviewer</option><option>Researcher</option></select></label><button disabled={busy}>Send invitation</button></form></div>}
    <div className="panel"><h2>Import older browser records</h2><p className="muted">Older records were shared on this browser. Inspect each record and import only your own proposal text. Historical analysis and decisions are not verified and will not be imported.</p><button disabled={busy} onClick={() => void act(async () => { const records: unknown = JSON.parse(localStorage.getItem('patentintel_db_innovation_projects') || '[]'); if (!Array.isArray(records)) throw Error('Older records have an unsupported format.'); setLegacy(records.filter(r => r && typeof r.id === 'string' && typeof r.title === 'string' && typeof r.description === 'string' && !r.id.startsWith('preset') && !r.id.startsWith('proj_preset_')).map(r => ({ id: r.id, title: r.title, description: r.description }))); setInspected(true); })}>Inspect browser records</button>{inspected && !legacy.length && <p>No eligible older records found.</p>}{legacy.map(record => <details key={record.id}><summary>{record.title}</summary><pre>{record.description}</pre><button disabled={busy} onClick={() => void act(async () => { await pilotApi('/projects', { title: record.title, proposal: record.description, features: [] }); setLegacy(records => records.filter(r => r.id !== record.id)); }, 'Proposal text imported into your account.')}>Import this proposal into my account</button></details>)}<p><button disabled={busy} onClick={() => void act(async () => { localStorage.removeItem('PATENTINTEL_SETTINGS'); }, 'Legacy browser provider settings removed.')}>Remove legacy browser API settings</button></p></div>
  </>;
}

export default function PilotApp() {
  const [user, setUser] = useState<SessionUser | null>(null), [restoring, setRestoring] = useState(true), [serviceError, setServiceError] = useState('');
  const [route, setRoute] = useState(parseRoute), [menu, setMenu] = useState(false), [projects, setProjects] = useState<Project[]>([]), [reviews, setReviews] = useState<Review[]>([]), [users, setUsers] = useState<SessionUser[]>([]);
  const [detail, setDetail] = useState<ProjectDetail | null>(null), [sources, setSources] = useState<Source[]>([]);
  const [loading, setLoading] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState('');
  const [creating, setCreating] = useState(false), [newTitle, setNewTitle] = useState('');
  const generation = useRef(0), mutation = useRef(false), previousHash = useRef(location.hash);
  useEffect(() => {
    let active = true;
    const restore = async () => { try { const restored = await authClient.session(); if (active) { setUser(restored); setServiceError(''); } } catch (e) { if (active) setServiceError((e as Error).message); } finally { if (active) setRestoring(false); } };
    void restore();
    const timer = setInterval(restore, 60000);
    const expired = () => { authClient.clearSession(); generation.current++; setUser(null); setDetail(null); setProjects([]); setReviews([]); setServiceError('Your session expired. Sign in again to continue.'); };
    window.addEventListener('pilot-session-expired', expired);
    window.addEventListener('focus', restore);
    return () => { active = false; clearInterval(timer); window.removeEventListener('focus', restore); window.removeEventListener('pilot-session-expired', expired); };
  }, []);
  useEffect(() => {
    document.getElementById('pilot-content')?.focus();
  }, [route.view, route.id, route.version]);
  useEffect(() => {
    if (!menu) return;
    const closeMenu = (event: KeyboardEvent) => {
      if (event.key === 'Escape') {
        setMenu(false);
        document.getElementById('pilot-menu-toggle')?.focus();
      }
    };
    window.addEventListener('keydown', closeMenu);
    return () => window.removeEventListener('keydown', closeMenu);
  }, [menu]);
  const userId = user?.id, userRole = user?.role;
  const load = useCallback(async () => {
    if (!userId) return;
    const n = ++generation.current; setLoading(true);
    try {
      const [p, r, u, d] = await Promise.all([pilotApi<{ projects: Project[] }>('/projects'), pilotApi<{ reviews: Review[] }>('/reviews'), userRole === 'Administrator' ? pilotApi<{ users: SessionUser[] }>('/admin/users') : Promise.resolve({ users: [] }), route.id ? pilotApi<ProjectDetail>(`/projects/${route.id}`) : Promise.resolve(null)]);
      const s = d?.project.canEdit ? await pilotApi<{ sources: Source[] }>(`/sources?projectId=${d.project.id}`) : { sources: [] };
      if (n !== generation.current) return;
      setProjects(p.projects); setReviews(r.reviews); setUsers(u.users); setDetail(d); setSources(s.sources); setError('');
    } catch (e) { if (n === generation.current) throw e; } finally { if (n === generation.current) setLoading(false); }
  }, [userId, userRole, route.id]);
  useEffect(() => { setDetail(null); void load().catch(e => setError(e.message)); return () => { generation.current++; }; }, [load]);
  useEffect(() => { const hash = () => { if (document.documentElement.dataset.pilotDirty === 'true' && !confirm('Leave this draft without saving your changes?')) { history.replaceState(null, '', previousHash.current || '#/pilot/dashboard'); return; } if (document.documentElement.dataset.pilotDirty === 'true') removeDraft(document.documentElement.dataset.pilotDraftKey || ''); previousHash.current = location.hash; const next = parseRoute(); setRoute(next); setMenu(false); setNotice(''); }; window.addEventListener('hashchange', hash); return () => window.removeEventListener('hashchange', hash); }, []);
  const navigate = (view: View, id = '', requestedVersion?: string) => { location.hash = pilotHash(view, id, requestedVersion ?? (id === route.id ? route.version || detail?.versions[0]?.id || '' : '')); };
  const act: Act = async (operation, message) => { if (mutation.current) return; mutation.current = true; setBusy(true); setError(''); setNotice(''); try { await operation(); if (message) setNotice(message); } catch (e) { setError((e as Error).message); } finally { mutation.current = false; setBusy(false); } };
  const updated = async (newVersionId?: string) => { await load(); if (newVersionId) navigate(route.view, route.id, newVersionId); };
  const version = detail ? selectedVersion(detail.versions, route.version) : undefined;
  const active = projects.filter(p => !p.archived), pending = reviews.filter(r => ['SUBMITTED', 'RESUBMITTED', 'UNDER_REVIEW'].includes(r.status));
  const heading = navigation.find(n => n[0] === route.view)?.[1];
  if (restoring) return <div className="pilot-loading" role="status">Opening your research workspace…</div>;
  if (!user || ['reset', 'verify', 'invite'].some(key => new URLSearchParams(location.search).has(key))) return <AuthScreen onLoginSuccess={u => { generation.current++; setDetail(null); setProjects([]); setReviews([]); setUser(u); setServiceError(''); }} serviceError={serviceError} />;
  const props = detail && version ? { detail, version, user, users, sources, act, busy, updated } : null;
  const projectList = <div className="project-list">{!projects.length && <div className="empty"><FileText size={32} /><h3>Your ideas start here</h3><p>Create your first proposal to collect evidence and invite a review.</p></div>}{projects.map(p => <button className="project-row" key={p.id} onClick={() => navigate(route.view === 'dashboard' ? 'proposals' : route.view, p.id)}><span className="project-icon"><FileText size={22} /></span><span><strong>{p.title}</strong><small>{p.owner_name} · Version {p.revision} · {new Date(p.updated_at).toLocaleDateString()}</small></span><span className="badge">{p.archived ? 'archived' : readable(p.status || 'DRAFT')}</span><ArrowUpRight size={18} /></button>)}</div>;
  return <div className="pilot-app"><a className="skip-link" href="#pilot-content" onClick={e => { e.preventDefault(); document.getElementById('pilot-content')?.focus(); }}>Skip to content</a><aside id="pilot-navigation" className={menu ? 'pilot-sidebar is-open' : 'pilot-sidebar'}><a className="pilot-brand" href="#/pilot/dashboard"><Fingerprint size={32} /><span>PatentIntel<span className="brand-dot">.AI</span><small>RESEARCH WORKSPACE</small></span></a><p className="nav-caption">WORKSPACE</p><nav aria-label="Main navigation">{navigation.map(([id, label, Icon]) => <button aria-current={route.view === id ? 'page' : undefined} key={id} onClick={() => navigate(id, ['sources', 'reports'].includes(id) ? route.id : '')}><Icon size={20} />{label}</button>)}</nav><div className="sidebar-note"><span className="status-dot" /> Evidence-led research<p>Clear sources. Thoughtful reviews.<br />A traceable path forward.</p></div><div className="sidebar-profile"><span className="avatar">{user.name.slice(0, 1).toUpperCase()}</span><span><strong>{user.name}</strong><small>{user.role}</small></span><button aria-label="Sign out" disabled={busy} onClick={() => { if (document.documentElement.dataset.pilotDirty === 'true' && !confirm('Sign out without saving this draft?')) return; void act(async () => { await authClient.logout(); clearDrafts(); generation.current++; setUser(null); setDetail(null); setProjects([]); setReviews([]); }); }}><LogOut size={18} /></button></div></aside>
    <div className="pilot-main"><header className="pilot-topbar"><button id="pilot-menu-toggle" className="menu-toggle" aria-controls="pilot-navigation" aria-label="Toggle navigation" aria-expanded={menu} onClick={() => setMenu(!menu)}><Menu /></button><span>Workspace <span className="muted">/ {heading}</span></span><div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginLeft: 'auto' }}><a href="#/dashboard" className="platform-nav-link">← Open Patent Platform (12 Modules)</a><span className="workspace-label">Research team pilot</span></div></header><main id="pilot-content" tabIndex={-1}><div className="page-heading"><div><p className="eyebrow">YOUR RESEARCH, CONNECTED</p><h1>{heading}</h1></div>{['dashboard', 'proposals'].includes(route.view) && <button className="primary" onClick={() => setCreating(!creating)}><Plus size={18} />New proposal</button>}</div>
    {error && <div className="error" role="alert">{error} <button disabled={busy} onClick={() => void act(load)}>Retry loading</button></div>}{notice && <div className="notice" role="status">{notice}</div>}{serviceError && <div className="error" role="alert">{serviceError}</div>}{busy && <p role="status" className="muted">Saving your changes…</p>}
    {creating && <form className="panel create-form" onSubmit={e => { e.preventDefault(); void act(async () => { const p = await pilotApi<{ id: string }>('/projects', { title: newTitle, features: [] }); setNewTitle(''); setCreating(false); navigate('proposals', p.id); await load(); }, 'Proposal created. Add your text and technical features.'); }}><h2>Give your proposal a name</h2><label>Proposal title<input autoFocus required maxLength={200} value={newTitle} onChange={e => setNewTitle(e.target.value)} placeholder="e.g. Low-power water quality monitoring" /></label><div className="button-row"><button className="primary" disabled={busy}>Create proposal</button><button type="button" onClick={() => setCreating(false)}>Cancel</button></div></form>}
    {loading && !detail && <p role="status">Loading your workspace…</p>}
    {route.view === 'dashboard' && <><section className="pilot-hero"><div><p className="eyebrow">FROM IDEA TO INFORMED DECISION</p><h2>Make room for your<br />next discovery.</h2><p>Build your proposal, follow the evidence,<br />and move forward with a considered review.</p><button onClick={() => setCreating(true)}>Start a proposal <ArrowUpRight size={18} /></button></div><div className="hero-orbit" aria-hidden="true"><Fingerprint size={120} strokeWidth={0.65} /><span>EVIDENCE → INSIGHT</span></div></section><div className="stat-grid"><div><span>Active proposals</span><strong>{active.length}</strong></div><div><span>Awaiting review</span><strong>{pending.length}</strong></div><div><span>Needs revision</span><strong>{active.filter(p => p.status === 'NEEDS_REVISION').length}</strong></div></div><div className="section-heading"><h2>Your proposals</h2><button onClick={() => navigate('proposals')}>View all <ArrowUpRight size={16} /></button></div>{projectList}<div className="panel"><h2>Next actions</h2>{!pending.length && !active.some(p => p.status === 'NEEDS_REVISION') ? <p className="muted">No pending reviews. Continue a draft or start a new proposal.</p> : <>{pending.map(r => <p key={r.id}><button onClick={() => navigate('reviews', r.project_id, r.version_id)}>{r.title} · Version {r.number} · {readable(r.status)}</button></p>)}{active.filter(p => p.status === 'NEEDS_REVISION').map(p => <p key={p.id}><button onClick={() => navigate('proposals', p.id)}>Revise {p.title}</button></p>)}</>}</div></>}
    {route.view === 'settings' && <AccountSettings user={user} setUser={setUser} act={act} busy={busy} />}
    {!['dashboard', 'settings'].includes(route.view) && <>{route.id && <button className="back-link" onClick={() => navigate(route.view)}>← All {route.view === 'reviews' ? 'reviews' : 'proposals'}</button>}{!route.id && <>{route.view === 'reviews' ? <div className="panel"><h2>Review queue</h2>{!reviews.length && <p className="empty">No submissions yet. Assigned reviewers see a proposal here after its author submits it.</p>}{reviews.map(r => <button className="project-row" key={r.id} onClick={() => { navigate('reviews', r.project_id, r.version_id); }}><span><strong>{r.title}</strong><small>Version {r.number} · {r.owner_name}</small></span><span className="badge">{readable(r.status)}</span><ArrowUpRight size={18} /></button>)}</div> : <><p className="muted">Choose a proposal to {route.view === 'sources' ? 'search sources and inspect its evidence' : route.view === 'reports' ? 'export a version report' : 'continue working'}.</p>{projectList}</>}</>}{detail && route.version && !version && <div className="error" role="alert">This proposal version is unavailable or you do not have access to it. <button onClick={() => navigate(route.view, route.id, detail.versions[0]?.id || '')}>Open latest accessible version</button></div>}{props && <><div className="version-toolbar"><div><strong>{detail!.project.title}</strong>{detail!.project.archived && <span className="badge">Archived</span>}</div><label>Version<select value={version!.id} onChange={e => { navigate(route.view, route.id, e.target.value); }}>{detail!.versions.map(v => <option value={v.id} key={v.id}>Version {v.number} · {new Date(v.created_at).toLocaleDateString()}</option>)}</select></label></div><nav className="proposal-tabs" aria-label="Proposal sections">{(['proposals', 'sources', 'reviews', 'reports'] as const).map(v => <button key={v} aria-current={route.view === v ? 'page' : undefined} onClick={() => navigate(v, route.id)}>{v === 'proposals' ? 'Proposal' : v === 'sources' ? 'Evidence' : v === 'reviews' ? 'Review' : 'Report'}</button>)}</nav>{route.view === 'proposals' && <ProposalEditor key={version!.id} {...props} />}{route.view === 'sources' && <SourcesPanel key={version!.id} {...props} />}{route.view === 'reviews' && <ReviewPanel key={version!.id} {...props} />}{route.view === 'reports' && <ReportPanel key={version!.id} {...props} />}</>}</>}
    <footer className="pilot-footer">PatentIntel.AI · Transparent research, considered decisions.</footer></main></div></div>;
}
